apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nextcloud.yaml
  - redis.yaml
  - postgres.yaml

# This section makes it easy for the CI/CD pipeline to update the tag
images:
  - name: ghcr.io/goeasycare/nextcloud-custom
    newName: ghcr.io/goeasycare/nextcloud-custom
    newTag: latest
