apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nextcloud-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
          - cluster: remote-cluster
            url: https://kubernetes.default.svc
          - branch: nextcloud-argo
  template:
    metadata:
      name: nextcloud
    spec:
      project: default
      source:
        repoURL: https://github.com/goeasycare/nextcloud-scenarios
        targetRevision: '{{branch}}'
        path: sample/app
      destination:
        server: '{{url}}'
        namespace: nextcloud
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
