apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-ingress
  namespace: argocd  # CHANGED: Must match EventSource namespace
  annotations:
    cert-manager.io/issuer: "origin-issuer"
    cert-manager.io/issuer-kind: "ClusterOriginIssuer"
    cert-manager.io/issuer-group: "cert-manager.k8s.cloudflare.com"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    # If you use Cert Manager for TLS:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:   # ADDED: Required for cert-manager to store the cert
  - hosts:
    - events.goeasycare.app
    secretName: events-tls
  rules:
  - host: events.goeasycare.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: github-event-source-eventsource-svc # EventSource creates a service where name is {{EventSource.metadata[0].name}}-eventsource-svc
            port:
              number: 12000 # CHANGED: Matches eventsource.yaml
